version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Rahul
      MYSQL_DATABASE: crud_app
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  backend:
    build: ./api
    container_name: backend_app
    ports:
      -"5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Rahul
      DB_NAME: crud_app
      JWT_SECRET: devopsSuperSecretKey
      RESET_ADMIN_PASS: 'true'

  frontend:
    build: ./client
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data:
