name: CI for Backend

on:
  push:
    branches:
      - main
      - local-dev
    paths:
      - "api/**"
      
  workflow_dispatch:

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v5
      - name: Node initialization
        uses: actions/setup-node@v6
      - name: Intall dependencies
        working-directory: api
        run: npm install
  
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Deploy
        run: echo "Deploying .....!!"